Resources:
  FuncServiceRole49680D06:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/ServiceRole/Resource
  Func217E03A4:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: FuncCodeS3Bucket3BC06A54
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: FuncCodeS3VersionKey92D37064
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: FuncCodeS3VersionKey92D37064
      Handler: lambda_function.handler
      Role:
        Fn::GetAtt:
          - FuncServiceRole49680D06
          - Arn
      Runtime: python3.7
    DependsOn:
      - FuncServiceRole49680D06
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/Resource
      aws:asset:path: /Users/pahud/github/cdk-samples/function/hello-world
      aws:asset:property: Code
  FuncApiPermissionServerlessAPIRestApi19FC4B79ANY8607DCA9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Func217E03A4
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-2:903779448426:"
            - Ref: RestApi0C43BF4B
            - /
            - Ref: RestApiDeploymentStageprod3855DE66
            - /*/
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/ApiPermission.ServerlessAPIRestApi19FC4B79.ANY..
  FuncApiPermissionTestServerlessAPIRestApi19FC4B79ANY8AEC8F14:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Func217E03A4
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-2:903779448426:"
            - Ref: RestApi0C43BF4B
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/ApiPermission.Test.ServerlessAPIRestApi19FC4B79.ANY..
  FuncApiPermissionServerlessAPIRestApi19FC4B79ANYproxy9FC92149:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Func217E03A4
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-2:903779448426:"
            - Ref: RestApi0C43BF4B
            - /
            - Ref: RestApiDeploymentStageprod3855DE66
            - /*/{proxy+}
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/ApiPermission.ServerlessAPIRestApi19FC4B79.ANY..{proxy+}
  FuncApiPermissionTestServerlessAPIRestApi19FC4B79ANYproxy981A5288:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Func217E03A4
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-2:903779448426:"
            - Ref: RestApi0C43BF4B
            - /test-invoke-stage/*/{proxy+}
    Metadata:
      aws:cdk:path: ServerlessAPI/Func/ApiPermission.Test.ServerlessAPIRestApi19FC4B79.ANY..{proxy+}
  RestApi0C43BF4B:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Resource
  RestApiDeployment180EC50362ac53de42001ec390092fd2d2445cca:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RestApi0C43BF4B
      Description: Automatically created by the RestApi construct
    DependsOn:
      - RestApiproxyANY1786B242
      - RestApiproxyC95856DD
      - RestApiANYA7C1DC94
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Deployment/Resource
  RestApiDeploymentStageprod3855DE66:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: RestApi0C43BF4B
      DeploymentId:
        Ref: RestApiDeployment180EC50362ac53de42001ec390092fd2d2445cca
      StageName: prod
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/DeploymentStage.prod/Resource
  RestApiCloudWatchRoleE3ED6605:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/CloudWatchRole/Resource
  RestApiAccount7C83CF5A:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - RestApiCloudWatchRoleE3ED6605
          - Arn
    DependsOn:
      - RestApi0C43BF4B
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Account
  RestApiproxyC95856DD:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - RestApi0C43BF4B
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: RestApi0C43BF4B
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Default/{proxy+}/Resource
  RestApiproxyANY1786B242:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: RestApiproxyC95856DD
      RestApiId:
        Ref: RestApi0C43BF4B
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - Func217E03A4
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Default/{proxy+}/ANY/Resource
  RestApiANYA7C1DC94:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - RestApi0C43BF4B
          - RootResourceId
      RestApiId:
        Ref: RestApi0C43BF4B
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - Func217E03A4
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ServerlessAPI/RestApi/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.6.1,@aws-cdk/assets=1.6.1,@aws-cdk/aws-apigateway=1.6.1,@aws-cdk/aws-cloudwatch=1.6.1,@aws-cdk/aws-ec2=1.6.1,@aws-cdk/aws-events=1.6.1,@aws-cdk/aws-iam=1.6.1,@aws-cdk/aws-kms=1.6.1,@aws-cdk/aws-lambda=1.6.1,@aws-cdk/aws-s3=1.6.1,@aws-cdk/aws-s3-assets=1.6.1,@aws-cdk/aws-sqs=1.6.1,@aws-cdk/aws-ssm=1.6.1,@aws-cdk/core=1.6.1,@aws-cdk/cx-api=1.6.1,@aws-cdk/region-info=1.6.1,jsii-runtime=node.js/v10.16.0
Parameters:
  FuncCodeS3Bucket3BC06A54:
    Type: String
    Description: S3 bucket for asset "ServerlessAPI/Func/Code"
  FuncCodeS3VersionKey92D37064:
    Type: String
    Description: S3 key for asset version "ServerlessAPI/Func/Code"
  FuncCodeArtifactHashABA8973E:
    Type: String
    Description: Artifact hash for asset "ServerlessAPI/Func/Code"
Outputs:
  RestApiEndpoint0551178A:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: RestApi0C43BF4B
          - .execute-api.us-west-2.
          - Ref: AWS::URLSuffix
          - /
          - Ref: RestApiDeploymentStageprod3855DE66
          - /

